name: 📦 Build

on:
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.13"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python and uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.5.2"

      - name: Install dependencies
        run: uv sync -p ${{ env.PYTHON_VERSION }}

      - name: Run linting
        run: uv run poe lint

      - name: Run tests
        run: uv run poe test
